### ISSUE TITLE
Output not found by script

### ISSUE THREAD

**Issue by MenonPlayz** [westarne/voicemeeter-auto-restart#2]
I did update voicemeeter a while back because something was lagging.
After that, this very useful plugin didnt work anymore on my loudspeakers connected through my PC monitor.

The script prints this every few seconds:
Unavailable Outputs: ['MAG274QRF-QD (High Definition Audio Device)']
Unavailable Inputs: []

![grafik](https://github.com/westarne/voicemeeter-auto-restart/assets/90968284/f5770e15-ad72-413e-9841-1202ec8c7232)
![grafik](https://github.com/westarne/voicemeeter-auto-restart/assets/90968284/b49f3136-4d93-4bd2-b490-8ba169b64f1b)
I have to select this every time in voicemeeter (picture 1), even when my computer clearly recognizes the monitor (picture 2).

Can't really tell what is causing the issue, maybe it has something to do with the naming, as windows shows "NVIDIA High Definition Audio Device" and the script only "High Definition Audio Device".

**Comment by westarne** [comment]
Hi @MenonPlayz,

first of all a short disclaimer: I'm currently not actively using Windows and thus not using Voicemeeter. Latest version I have used was `Voicemeeter Potato 3.0.2.8` and there it was at least correctly working (as far as I remember, even with similarly named Devices). So from my side a few ideas of what could be the problem, though I'll not be able to actively test a newer version at the moment to see if it's a problem with the script itself.

1. If you have copied the Voicemeeter dll mentioned in the readme into the script directory it might be worth it do repeat that and copy the latest .dll. I don't really expect this to be the problem, but it could be an option.
2. If this doesn't help or you have copied the script into Voicemeeter (so the other way around), you could try re-activating the devices within Voicemeeter explicitly. So in your output selection (A1 - AX) deselect your device and re-select it afterwards (potentially even restart Voicemeeter in between). This could potentially clean up some internal Voicemeeter state.

Background of idea 2: the script is solely working on what Voicemeeter offers as information. If voicemeeter in it's internal state still lists this device under a different name, this could be the cause. Re-setting the device might update this. I could think of some Voicemeeter internal scenarios where this could happen, though I of course don't know that code. So I cannot check it.

Having it listed as "Unavailable Output" definitely tells me 2 things: the Voicemeeter thinks that this device is selected (what is most likely correct, but maybe the name slightly changed due to some update), Voicemeeter does not find a device with the identical name to be available. So that could mean, that the selected device in voicemeeter is outdated and not actually matching your device anymore (would need a refresh of the voicemeeter state mentioned above), or that something changed so that the device names are not enough to compare them anymore (would need a code change of the script).

So the second option means that the script is not compatible with your version of Voicemeeter OR there is a problem with the device name, but then it'll be hard for me to test/update that at the moment.

I hope this helps, would be great if you can reply back either way. Otherwise if I have the time and a windows machine again, I'll potentially test it there.

**Comment by MenonPlayz** [comment]
@westarne Thank you so much for the insight! 
I did some checking of what my actual setup was and figured that I had my settings file configured wrong. I would always save my config to a file which wasnt the one I selected to apply at startup in voicemeeter.
It does seem to work again after rebooting my PC. 
I hope this fixed my issue long term. Great tool you made for sure!
